server:
  port: 9090

spring:
  application:
    name: mcp-server
  
  # WebFlux配置 - 解决大数据量传输问题
  webflux:
    max-in-memory-size: 10MB
  codec:
    max-in-memory-size: 10MB
  
  # 数据库配置
  datasource:
    url: jdbc:postgresql://localhost:15432/sp
    username: "postgres"
    password: "123456"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# API基础URL配置（用于数据库工具的URL构建）
api:
  base-url: "http://116.63.146.89:60011"

# MCP客户端配置（用于SSE推送）
mcp:
  client:
    base-url: "http://localhost:8080"

logging:
  level:
    com.guian.smartsite.server: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
